sudo: required 
services:
  - docker

before_install:
  - docker build -t sanxeez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sanxeez/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Frontend"
  env: "Frontend-dev-1"
  bucket_name: "elasticbeanstalk-eu-west-1-288926701519"
  bucket_path: "Frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"